apiVersion: v1
kind: Service
metadata:
    name: "testdp5-99e8"
    labels:
        app: "testdp5-99e8"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "testdp5-99e8"